# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Comments
comments:         true

# Setup
title:            Michael
tagline:          'Tech Enthusiast'
description:      'To Software , Hardware and Users.'
url:              http://michaelokuboyejo.github.io

author:
  name:           'Michael Okuboyejo'
  url:            https://twitter.com/mykelokuboyejo

paginate:         5

analytics :
  provider : google 
  google : 
      tracking_id : 'UA-65915501-1'

# Custom vars
version:          2.0.0

#github:
#  repo:           https://github.com/poole/hyde